<?php
return [
    [
        'POST',
        '/transactions',
        [
            'App\Controllers\TransactionController',
            'queueTransaction'
        ]
    ],
    [
        'POST',
        '/test',
        [
            'App\Controllers\TransactionController',
            'insertTransaction'
        ]
    ]
];